annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 0.1.0
description: Kubewatch notifies your slack rooms when changes to your cluster occur
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/kubewatch
icon: https://bitnami.com/assets/stacks/kubewatch/img/kubewatch-stack-220x234.png
keywords:
  - kubernetes
  - slack
  - hipchat
  - mattermost
  - flock
  - msteams
maintainers:
  - email: casey@monax.io
    name: compleatang
  - email: containers@bitnami.com
    name: Bitnami
name: kubewatch
sources:
  - https://github.com/bitnami/bitnami-docker-kubewatch
  - https://github.com/bitnami-labs/kubewatch
version: 2.0.0
